"""empty message

Revision ID: 5948d0bfd125
Revises: f145d86f4d3c
Create Date: 2023-05-01 22:04:58.511433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5948d0bfd125'
down_revision = 'f145d86f4d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('latest_users')
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('api_recipe')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('api_recipe')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_recipe', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_recipe', sa.BOOLEAN(), nullable=True))

    op.create_table('latest_users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    # ### end Alembic commands ###
