"""empty message

Revision ID: 694bb1b5004a
Revises: 46e7d22c3b68
Create Date: 2023-05-09 14:43:16.735001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694bb1b5004a'
down_revision = '46e7d22c3b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
