"""empty message

Revision ID: 7206e067e845
Revises: 
Create Date: 2023-04-17 12:50:53.826646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7206e067e845'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('sourceUrl', sa.String(), nullable=True),
    sa.Column('cooking_mins', sa.Integer(), nullable=True),
    sa.Column('prep_mins', sa.Integer(), nullable=True),
    sa.Column('ready_mins', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('username', sa.String(length=75), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('equpiment',
    sa.Column('equpment_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], ),
    sa.PrimaryKeyConstraint('equpment_id')
    )
    op.create_table('ingredients',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('recipe_ing_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(precision=2), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], ),
    sa.PrimaryKeyConstraint('recipe_ing_id')
    )
    op.create_table('instructions',
    sa.Column('instruction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('step_num', sa.Integer(), nullable=True),
    sa.Column('step_instruction', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], ),
    sa.PrimaryKeyConstraint('instruction_id')
    )
    op.create_table('saved_recipes',
    sa.Column('saved_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('favorited', sa.Boolean(), nullable=True),
    sa.Column('tried', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('commented', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('saved_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_recipes')
    op.drop_table('instructions')
    op.drop_table('ingredients')
    op.drop_table('equpiment')
    op.drop_table('user')
    op.drop_table('recipes')
    # ### end Alembic commands ###
