"""empty message

Revision ID: ddc73a8e8f0d
Revises: 00f378fa5132
Create Date: 2023-05-06 18:00:37.866522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc73a8e8f0d'
down_revision = 'a975ed85d8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
        with op.batch_alter_table('recipe', schema=None) as batch_op:
            batch_op.alter_column('title',
                existing_type=sa.VARCHAR(length=200),
                nullable=False) # make title column non-nullable
        op.execute("DELETE FROM recipe WHERE title IS NULL")
       
    # ### end Alembic commands ###
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table('recipe', schema=None) as batch_op:
                batch_op.alter_column('title',
                    existing_type=sa.VARCHAR(length=200),
                    nullable=True)
            
        
        # ### end Alembic commands ###
